// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu45QaTvmh_-X_poAxOjDyqfa6UUVbwzg',
    appId: '1:816830288773:web:440747784ec373be682aec',
    messagingSenderId: '816830288773',
    projectId: 'alon-finance-final',
    authDomain: 'alon-finance-final.firebaseapp.com',
    storageBucket: 'alon-finance-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkyzkcCAGwdasq8ghmvFvZNS9HUBvACU',
    appId: '1:816830288773:android:8b2ba40cd60b29eb682aec',
    messagingSenderId: '816830288773',
    projectId: 'alon-finance-final',
    storageBucket: 'alon-finance-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--hnpS4YbKwnKQ6wIcY2UYlJuypbaPTE',
    appId: '1:816830288773:ios:98c6d944231cc018682aec',
    messagingSenderId: '816830288773',
    projectId: 'alon-finance-final',
    storageBucket: 'alon-finance-final.firebasestorage.app',
    iosBundleId: 'com.example.familyBizFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--hnpS4YbKwnKQ6wIcY2UYlJuypbaPTE',
    appId: '1:816830288773:ios:98c6d944231cc018682aec',
    messagingSenderId: '816830288773',
    projectId: 'alon-finance-final',
    storageBucket: 'alon-finance-final.firebasestorage.app',
    iosBundleId: 'com.example.familyBizFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu45QaTvmh_-X_poAxOjDyqfa6UUVbwzg',
    appId: '1:816830288773:web:50a927496c48439a682aec',
    messagingSenderId: '816830288773',
    projectId: 'alon-finance-final',
    authDomain: 'alon-finance-final.firebaseapp.com',
    storageBucket: 'alon-finance-final.firebasestorage.app',
  );
}
